fix makefile bug

diff --git a/include/Makefile.targets b/include/Makefile.targets
--- a/include/Makefile.targets
+++ b/include/Makefile.targets
@@ -1,6 +1,8 @@
 all: $(APPROM)
-	@$(SHA1SUM) -c ge007.$(COUNTRYCODE).sha1 || (echo "\n    ERROR!\n\n\n    NOT MATCH!\n\n" && exit 1)
-	@echo "\n    MATCH!\n\n"
+	@if [ -f ge007.$(OUTCODE).sha1 ]; then \
+		$(SHA1SUM) -c ge007.$(OUTCODE).sha1 || (echo "\n    ERROR!\n\n\n    NOT MATCH!\n\n" && exit 1); \
+		echo "\n    MATCH!\n\n"; \
+	fi
 	@echo "\nRom File Generated in Build Directory. \n\n"
 
 .SECONDARY:
